framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        auto_mapping:
           App\Entity\: [
               id:Blank,
               name:NotBlank,
               description:NotBlank,
               image:NotBlank,
               price:NotBlank,
               sale_price:NotBlank,
           ]

when@test:
    framework:
        validation:
            not_compromised_password: false
